### ISSUE TITLE
HTML header

### ISSUE THREAD

**Issue by xydro4** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#17]
Can we have support for an HTML header like there is support for the HTML footer?

**Comment by madnight** [comment]
I'll check that ` --header-html` should be analog to `--footer-html`

**Comment by madnight** [comment]
i created a new branch https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/tree/header that supports a header which works the same way as the footer

carefully look at the corresponding updated test https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/commit/3112508431cbbaa6babafd64f8442c8e32f382f4#diff-d6c3e36ba681120ef6d2f240e9e8c6cf, because the header can behave unexpected (e.g header-spacing is required without mm suffix) and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1576 (DOCTYPE required) but it should work

**Comment by madnight** [comment]
merged
