### ISSUE TITLE
Error with font size

### ISSUE THREAD

**Issue by pmorelli92** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#20]
Hello,

I am having a problem when converting an HTML to the PDF. The PDF is ignoring the font size.

The HTML to reproduce is attached: [Reproduce.zip](https://github.com/traum-ferienwohnungen/docker-wkhtmltopdf-aas/files/1952967/Reproduce.zip)

When calling the container I can reproduce it using options (width & height) or without options.
When using the wkhtml from the command line the PDF is generated well:

`wkhtmltopdf reproduce.html reproduce.pdf`

So maybe it is because the docker image is using an old version?

Regards!

**Comment by pmorelli92** [comment]
I've just seen that the Dockerfile is using `https://downloads.wkhtmltopdf.org/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb` meanwhile the latest version is 0.12.0.4

**Comment by madnight** [comment]
you could try to update the version in the docker container and create a pull request if it solves the issue

**Comment by pmorelli92** [comment]
#21 Added the PR for adding font infinity.

I did not update the version of the wkhtmltopdf because it changes the dpi size and it seems the option json when invoking the call cannot change the dpi default.

The dockerfile for updating the wkhtmltopdf version and adding font-infinity is this one

```
FROM ubuntu:16.04
MAINTAINER Fabian Beuke <beuke@traum-ferienwohnungen.de>

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:no1wantdthisname/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends npm wget xz-utils build-essential \
    fontconfig fontconfig-infinality freetype2-demos libx11-6 libxext6 libxrender1 apt-utils \
    libcurl4-gnutls-dev librtmp-dev curl python-software-properties && \
    wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz && \
    tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz && \
    mv wkhtmltox/bin/wkhtmlto* /usr/bin/ && \
    ln -nfs /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y nodejs

RUN npm install -g yarn coffeescript forever bootprint bootprint-openapi

# generate documentation from swagger
COPY swagger.yaml /
RUN bootprint openapi swagger.yaml documentation && \
    npm uninstall -g bootprint bootprint-openapi

# install dependencies
COPY package.json /
RUN yarn install

COPY app.coffee /

EXPOSE 5555

RUN node --version && \
    npm --version && \
    coffee --version

CMD ["npm", "start"]
```

Can we get the image in Docker Hub updated?

**Comment by madnight** [comment]
Hi thx for the PR, i'll check it over the course of the next days. I will update the docker hub version on new release.

**Comment by madnight** [comment]
Hi, i rendered your `Reproduce.html` sample with the current master version and with the infinality font patchset.

Master:
<a href="https://i.imgur.com/GL3yuze.png">
  <img src="https://imgur.com/GL3yuzel.png" />
</a>

MR 21 (infinality font patchset):

<a href="https://i.imgur.com/JW7us3T.png">
  <img src="https://imgur.com/JW7us3Tl.png" />
</a>


As you can see the font size is about equal, only the font rendering is slightly different. I think the line break in the address / row spacing should be fixed with css.

**Comment by pmorelli92** [comment]
@madnight now try to exec wkhtmltopdf using your local machine. For example, in windows:

```
cd C:\Program Files\wkhtmltopdf\bin
wkhtmltopdf reproduce.html reproduce.pdf
```

And you can see that the generated PDF will look completely fine

![reproduce](https://user-images.githubusercontent.com/19840466/39501487-8cf1be68-4d91-11e8-88bd-ac57ec17ed50.png)

I think the problem here is with the font resizing, since it ignores my HTML:

```
.font-10{
	font-size:10pt;
}
```
That is why I tried solving it using font-infinality

**Comment by madnight** [comment]
Ok i've tried different versions of wkhtmltopdf and installed more fonts on ubuntu like `msttcorefonts`, all with different results. I think wkthmltopdf under ubuntu with linux available fonts != wkthmltopdf windows != chrome browser rendering. There are slightly different results depending on the OS, the HTML rendering engine and the installed fonts. I think the easiest fix for your problem is to edit the css, like so:

```patch
+.font-9 {
+	padding-top: 5px;
+	font-size:9pt;
+}
```
```patch
-	<div id="client" class="Client font-10">
+	<div id="client" class="Client font-9">
 		<div>
-			<p class="padding-left" style="font-size:10pt !important;" >Scalabrini Ortiz 1234 - Código Postal: 1442 - Ciudad: Capital Federal - Region: Capital Federal</p>
+			<p class="padding-left">Scalabrini Ortiz 1234 - Código Postal: 1442 - Ciudad: Capital Federal - Region: Capital Federal</p> 
```
And here is the result of the css edit: 

<a href="https://i.imgur.com/zy64nSG.png">
  <img src="https://imgur.com/zy64nSGl.png" />
</a>

**Comment by pmorelli92** [comment]
Hi @madnight, thank you for your help. I have 0 knowledge about CSS and I did not make the template, so I was trying to fix it on my own way since on Windows it was working fine.

**Comment by madnight** [comment]
Here is the updated template: [Reproduce.zip](https://github.com/traum-ferienwohnungen/docker-wkhtmltopdf-aas/files/1970453/Reproduce.zip)

Otherwise you could try another tool like https://github.com/esbenp/pdf-bot which utilizes headless chrome instead of wkhtmltopdf to create PDF's. It's based on Blink engine (instead of Qt WebKit), which is more likely to produce a result that exactly matches chrome's browser output.

**Comment by pmorelli92** [comment]
@madnight thank you very much. Well I will close the PR then. No need to merge the workaround.
